%General Mission Analysis Tool(GMAT) Script
%Created: 2015-04-07 06:24:03


%----------------------------------------
%---------- Solar System User-Modified Values
%----------------------------------------


GMAT SolarSystem.EphemerisSource = 'SPICE';
GMAT SolarSystem.UseTTForEphemeris = true;

%----------------------------------------
%---------- Calculated Points
%----------------------------------------

Create LibrationPoint Libration1;
GMAT Libration1.Primary = Sun;
GMAT Libration1.Secondary = Earth;
GMAT Libration1.Point = L1;

%----------------------------------------
%---------- Spacecraft
%----------------------------------------

Create Spacecraft DefaultSC;
GMAT DefaultSC.DateFormat = TDBModJulian;
GMAT DefaultSC.Epoch = '21545';
GMAT DefaultSC.CoordinateSystem = SunEarthL1MJ2000Ec;
GMAT DefaultSC.DisplayStateType = Cartesian;
GMAT DefaultSC.X = 0;
GMAT DefaultSC.Y = 0;
GMAT DefaultSC.Z = 0;
GMAT DefaultSC.VX = 0;
GMAT DefaultSC.VY = 0;
GMAT DefaultSC.VZ = 0;
GMAT DefaultSC.DryMass = 850;
GMAT DefaultSC.Cd = 2.2;
GMAT DefaultSC.Cr = 1.8;
GMAT DefaultSC.DragArea = 15;
GMAT DefaultSC.SRPArea = 1;
GMAT DefaultSC.NAIFId = -123456789;
GMAT DefaultSC.NAIFIdReferenceFrame = -123456789;
GMAT DefaultSC.Id = 'SatId';
GMAT DefaultSC.Attitude = CoordinateSystemFixed;
GMAT DefaultSC.ModelFile = '../data/vehicle/models/aura.3ds';
GMAT DefaultSC.ModelOffsetX = 0;
GMAT DefaultSC.ModelOffsetY = 0;
GMAT DefaultSC.ModelOffsetZ = 0;
GMAT DefaultSC.ModelRotationX = 0;
GMAT DefaultSC.ModelRotationY = 0;
GMAT DefaultSC.ModelRotationZ = 0;
GMAT DefaultSC.ModelScale = 3;
GMAT DefaultSC.AttitudeDisplayStateType = 'Quaternion';
GMAT DefaultSC.AttitudeRateDisplayStateType = 'AngularVelocity';
GMAT DefaultSC.AttitudeCoordinateSystem = EarthMJ2000Eq;
GMAT DefaultSC.EulerAngleSequence = '321';






%----------------------------------------
%---------- ForceModels
%----------------------------------------

Create ForceModel DefaultProp_ForceModel;
GMAT DefaultProp_ForceModel.CentralBody = Sun;
GMAT DefaultProp_ForceModel.PointMasses = {Earth, Sun};
GMAT DefaultProp_ForceModel.Drag = None;
GMAT DefaultProp_ForceModel.SRP = Off;
GMAT DefaultProp_ForceModel.RelativisticCorrection = Off;
GMAT DefaultProp_ForceModel.ErrorControl = RSSStep;

%----------------------------------------
%---------- Propagators
%----------------------------------------

Create Propagator DefaultProp;
GMAT DefaultProp.FM = DefaultProp_ForceModel;
GMAT DefaultProp.Type = RungeKutta89;
GMAT DefaultProp.InitialStepSize = 60;
GMAT DefaultProp.Accuracy = 9.999999999999999e-012;
GMAT DefaultProp.MinStep = 1;
GMAT DefaultProp.MaxStep = 27000;
GMAT DefaultProp.MaxStepAttempts = 50;
GMAT DefaultProp.StopIfAccuracyIsViolated = true;

%----------------------------------------
%---------- Burns
%----------------------------------------

Create ImpulsiveBurn DefaultIB;
GMAT DefaultIB.CoordinateSystem = Local;
GMAT DefaultIB.Origin = Earth;
GMAT DefaultIB.Axes = VNB;
GMAT DefaultIB.Element1 = 0;
GMAT DefaultIB.Element2 = 0;
GMAT DefaultIB.Element3 = 0;
GMAT DefaultIB.DecrementMass = false;
GMAT DefaultIB.Isp = 300;
GMAT DefaultIB.GravitationalAccel = 9.810000000000001;

%----------------------------------------
%---------- Coordinate Systems
%----------------------------------------

Create CoordinateSystem SunMJ2000Ec;
GMAT SunMJ2000Ec.Origin = Sun;
GMAT SunMJ2000Ec.Axes = MJ2000Ec;

Create CoordinateSystem SSBMJ2000Ec;
GMAT SSBMJ2000Ec.Origin = SolarSystemBarycenter;
GMAT SSBMJ2000Ec.Axes = MJ2000Ec;

Create CoordinateSystem SunEarthL1MJ2000Ec;
GMAT SunEarthL1MJ2000Ec.Origin = Libration1;
GMAT SunEarthL1MJ2000Ec.Axes = MJ2000Ec;

%----------------------------------------
%---------- Subscribers
%----------------------------------------

Create OrbitView DefaultOrbitView;
GMAT DefaultOrbitView.SolverIterations = Current;
GMAT DefaultOrbitView.UpperLeft = [ 0 0 ];
GMAT DefaultOrbitView.Size = [ 0.5 0.4494875549048316 ];
GMAT DefaultOrbitView.RelativeZOrder = 293;
GMAT DefaultOrbitView.Maximized = false;
GMAT DefaultOrbitView.Add = {DefaultSC, Earth, Sun};
GMAT DefaultOrbitView.CoordinateSystem = SSBMJ2000Ec;
GMAT DefaultOrbitView.DrawObject = [ true true true ];
GMAT DefaultOrbitView.OrbitColor = [ 255 32768 1743054 ];
GMAT DefaultOrbitView.TargetColor = [ 8421440 0 4227327 ];
GMAT DefaultOrbitView.DataCollectFrequency = 1;
GMAT DefaultOrbitView.UpdatePlotFrequency = 50;
GMAT DefaultOrbitView.NumPointsToRedraw = 0;
GMAT DefaultOrbitView.ShowPlot = true;
GMAT DefaultOrbitView.ViewPointReference = SolarSystemBarycenter;
GMAT DefaultOrbitView.ViewPointVector = [ 500000000 0 0 ];
GMAT DefaultOrbitView.ViewDirection = SolarSystemBarycenter;
GMAT DefaultOrbitView.ViewScaleFactor = 1;
GMAT DefaultOrbitView.ViewUpCoordinateSystem = SSBMJ2000Ec;
GMAT DefaultOrbitView.ViewUpAxis = Z;
GMAT DefaultOrbitView.EclipticPlane = Off;
GMAT DefaultOrbitView.XYPlane = On;
GMAT DefaultOrbitView.WireFrame = Off;
GMAT DefaultOrbitView.Axes = On;
GMAT DefaultOrbitView.Grid = Off;
GMAT DefaultOrbitView.SunLine = Off;
GMAT DefaultOrbitView.UseInitialView = On;
GMAT DefaultOrbitView.StarCount = 7000;
GMAT DefaultOrbitView.EnableStars = On;
GMAT DefaultOrbitView.EnableConstellations = On;

Create ReportFile ReportFile1;
GMAT ReportFile1.SolverIterations = Current;
GMAT ReportFile1.UpperLeft = [ 0.1155737704918033 0.2064421669106882 ];
GMAT ReportFile1.Size = [ 0.5885245901639344 0.7789165446559297 ];
GMAT ReportFile1.RelativeZOrder = 285;
GMAT ReportFile1.Maximized = false;
GMAT ReportFile1.Filename = 'Z:\home\ben\src\lisp\bld-orbit\gmat\ReportFile02Sun.txt';
GMAT ReportFile1.Precision = 16;
GMAT ReportFile1.Add = {DefaultSC.ElapsedSecs, DefaultSC.SunMJ2000Ec.X, DefaultSC.SunMJ2000Ec.Y, DefaultSC.SunMJ2000Ec.Z, DefaultSC.SunMJ2000Ec.VX, DefaultSC.SunMJ2000Ec.VY, DefaultSC.SunMJ2000Ec.VZ};
GMAT ReportFile1.WriteHeaders = true;
GMAT ReportFile1.LeftJustify = On;
GMAT ReportFile1.ZeroFill = Off;
GMAT ReportFile1.ColumnWidth = 20;
GMAT ReportFile1.WriteReport = true;

Create ReportFile ReportFile2;
GMAT ReportFile2.SolverIterations = Current;
GMAT ReportFile2.UpperLeft = [ 0 0 ];
GMAT ReportFile2.Size = [ 0 0 ];
GMAT ReportFile2.RelativeZOrder = 0;
GMAT ReportFile2.Maximized = false;
GMAT ReportFile2.Filename = 'Z:\home\ben\src\lisp\bld-orbit\gmat\ReportFile02SSB.txt';
GMAT ReportFile2.Precision = 16;
GMAT ReportFile2.Add = {DefaultSC.ElapsedSecs, DefaultSC.SSBMJ2000Ec.X, DefaultSC.SSBMJ2000Ec.Y, DefaultSC.SSBMJ2000Ec.Z, DefaultSC.SSBMJ2000Ec.VX, DefaultSC.SSBMJ2000Ec.VY, DefaultSC.SSBMJ2000Ec.VZ};
GMAT ReportFile2.WriteHeaders = true;
GMAT ReportFile2.LeftJustify = On;
GMAT ReportFile2.ZeroFill = Off;
GMAT ReportFile2.ColumnWidth = 20;
GMAT ReportFile2.WriteReport = true;


%----------------------------------------
%---------- Mission Sequence
%----------------------------------------

BeginMissionSequence;
Propagate DefaultProp(DefaultSC) {DefaultSC.ElapsedDays = 365.25};
