;;; Spacecraft data classes

(in-package :bld-orbit)

(defclass sc ()
  ((eom :initarg :eom :documentation "Equations of motion")
   (cb :initarg :cb :documentation "Central body")
   (sun :initarg :sun :documentation "Sun (if it's different from CB)")
   (gfun :initarg :gfun :documentation "Gravity function")
   (afun :initarg :afun :documentation "Sail acceleration function")
   (ofun :initarg :ofun :documentation "Orbital basis function")
   (pfun :initarg :pfun :documentation "Sail pointing function")
   (nfun :initarg :nfun :documentation "Function to call on sail body frame to get normal vector")
   (spfun :initarg :spfun :documentation "Solar pressure function")
   (lightness :initarg :lightness)
   (mass :initarg :mass :documentation "Mass of spacecraft (kg)")
   (area :initarg :area :documentation "Sail area (km^2, m^2*1d-6)")
   (optical :initarg :optical :documentation "Optical properties")
   (iframe :initarg :iframe :documentation "Inertial frame")
   (t0 :initarg :t0 :documentation "Initial time")
   (tf :initarg :tf :documentation "Final time")
   (x0 :initarg :x0 :documentation "Initial state")
   (rs :initarg :rs :documentation "Spacecraft orientation wrt orbit frame")
   (outfile :initarg :outfile :documentation "Output filename")
   (constants :initarg :constants :documentation "Extra constants used in EOM"))
  (:documentation "Spacecraft (solar sail) orbit problem"))
